#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_COMMA = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_COLON = 6,
  anon_sym_DQUOTE = 7,
  aux_sym_string_token1 = 8,
  anon_sym_COLON_COLON = 9,
  anon_sym_DOLLAR = 10,
  aux_sym__dollar_symbol_token1 = 11,
  sym__identifier = 12,
  anon_sym_SQUOTE = 13,
  aux_sym__quoted_symbol_token1 = 14,
  sym_source_file = 15,
  sym__value = 16,
  sym_struct = 17,
  sym_list = 18,
  sym_field_value_pair = 19,
  sym_string = 20,
  sym_annotations = 21,
  sym_symbol = 22,
  sym__dollar_symbol = 23,
  sym__quoted_symbol = 24,
  sym__field_name = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_struct_repeat1 = 27,
  aux_sym_list_repeat1 = 28,
  aux_sym_annotations_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_DOLLAR] = "$",
  [aux_sym__dollar_symbol_token1] = "_dollar_symbol_token1",
  [sym__identifier] = "_identifier",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__quoted_symbol_token1] = "_quoted_symbol_token1",
  [sym_source_file] = "source_file",
  [sym__value] = "_value",
  [sym_struct] = "struct",
  [sym_list] = "list",
  [sym_field_value_pair] = "field_value_pair",
  [sym_string] = "string",
  [sym_annotations] = "annotations",
  [sym_symbol] = "symbol",
  [sym__dollar_symbol] = "_dollar_symbol",
  [sym__quoted_symbol] = "_quoted_symbol",
  [sym__field_name] = "_field_name",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_annotations_repeat1] = "annotations_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym__dollar_symbol_token1] = aux_sym__dollar_symbol_token1,
  [sym__identifier] = sym__identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__quoted_symbol_token1] = aux_sym__quoted_symbol_token1,
  [sym_source_file] = sym_source_file,
  [sym__value] = sym__value,
  [sym_struct] = sym_struct,
  [sym_list] = sym_list,
  [sym_field_value_pair] = sym_field_value_pair,
  [sym_string] = sym_string,
  [sym_annotations] = sym_annotations,
  [sym_symbol] = sym_symbol,
  [sym__dollar_symbol] = sym__dollar_symbol,
  [sym__quoted_symbol] = sym__quoted_symbol,
  [sym__field_name] = sym__field_name,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_annotations_repeat1] = aux_sym_annotations_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__dollar_symbol_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quoted_symbol_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field_value_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_annotations] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__dollar_symbol] = {
    .visible = false,
    .named = true,
  },
  [sym__quoted_symbol] = {
    .visible = false,
    .named = true,
  },
  [sym__field_name] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_annotations_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 12,
        '$', 16,
        '\'', 19,
        ',', 6,
        ':', 11,
        '[', 8,
        ']', 9,
        '{', 5,
        '}', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(15);
      END_STATE();
    case 2:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 12,
        '$', 16,
        '\'', 19,
        ',', 6,
        ':', 1,
        '[', 8,
        ']', 9,
        '{', 5,
        '}', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 12,
        '$', 16,
        '\'', 19,
        ',', 6,
        ':', 10,
        '[', 8,
        ']', 9,
        '{', 5,
        '}', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(15);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__dollar_symbol_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__quoted_symbol_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__quoted_symbol_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 20},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 13},
  [49] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym__dollar_symbol_token1] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(43),
    [sym__value] = STATE(2),
    [sym_struct] = STATE(2),
    [sym_list] = STATE(2),
    [sym_string] = STATE(2),
    [sym_annotations] = STATE(12),
    [sym_symbol] = STATE(13),
    [sym__dollar_symbol] = STATE(10),
    [sym__quoted_symbol] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [sym__identifier] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
  },
  [2] = {
    [sym__value] = STATE(3),
    [sym_struct] = STATE(3),
    [sym_list] = STATE(3),
    [sym_string] = STATE(3),
    [sym_annotations] = STATE(12),
    [sym_symbol] = STATE(13),
    [sym__dollar_symbol] = STATE(10),
    [sym__quoted_symbol] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [sym__identifier] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
  },
  [3] = {
    [sym__value] = STATE(3),
    [sym_struct] = STATE(3),
    [sym_list] = STATE(3),
    [sym_string] = STATE(3),
    [sym_annotations] = STATE(12),
    [sym_symbol] = STATE(13),
    [sym__dollar_symbol] = STATE(10),
    [sym__quoted_symbol] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(24),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(30),
    [sym__identifier] = ACTIONS(33),
    [anon_sym_SQUOTE] = ACTIONS(36),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      sym_annotations,
    STATE(13), 1,
      sym_symbol,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(31), 4,
      sym__value,
      sym_struct,
      sym_list,
      sym_string,
  [38] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      sym_annotations,
    STATE(13), 1,
      sym_symbol,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(40), 4,
      sym__value,
      sym_struct,
      sym_list,
      sym_string,
  [76] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      sym_annotations,
    STATE(13), 1,
      sym_symbol,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(40), 4,
      sym__value,
      sym_struct,
      sym_list,
      sym_string,
  [114] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    STATE(12), 1,
      sym_annotations,
    STATE(13), 1,
      sym_symbol,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(40), 4,
      sym__value,
      sym_struct,
      sym_list,
      sym_string,
  [149] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    STATE(12), 1,
      sym_annotations,
    STATE(13), 1,
      sym_symbol,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(37), 4,
      sym__value,
      sym_struct,
      sym_list,
      sym_string,
  [184] = 2,
    ACTIONS(47), 1,
      anon_sym_COLON,
    ACTIONS(45), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_COLON_COLON,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [201] = 2,
    ACTIONS(51), 1,
      anon_sym_COLON,
    ACTIONS(49), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_COLON_COLON,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [218] = 2,
    ACTIONS(55), 1,
      anon_sym_COLON,
    ACTIONS(53), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_COLON_COLON,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [235] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(21), 4,
      sym_struct,
      sym_list,
      sym_string,
      sym_symbol,
  [264] = 3,
    ACTIONS(59), 1,
      anon_sym_COLON_COLON,
    STATE(41), 1,
      aux_sym_annotations_repeat1,
    ACTIONS(57), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [283] = 8,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      sym_field_value_pair,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(47), 3,
      sym_string,
      sym_symbol,
      sym__field_name,
  [311] = 8,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      sym_field_value_pair,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(47), 3,
      sym_string,
      sym_symbol,
      sym__field_name,
  [339] = 1,
    ACTIONS(65), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [353] = 8,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      sym_field_value_pair,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(47), 3,
      sym_string,
      sym_symbol,
      sym__field_name,
  [381] = 1,
    ACTIONS(69), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [394] = 1,
    ACTIONS(71), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [407] = 7,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    STATE(39), 1,
      sym_field_value_pair,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    STATE(47), 3,
      sym_string,
      sym_symbol,
      sym__field_name,
  [432] = 1,
    ACTIONS(73), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [445] = 1,
    ACTIONS(75), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [458] = 1,
    ACTIONS(77), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [471] = 1,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [484] = 1,
    ACTIONS(81), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [497] = 1,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [510] = 1,
    ACTIONS(85), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [523] = 3,
    STATE(46), 1,
      sym_symbol,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    ACTIONS(87), 6,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [539] = 3,
    STATE(46), 1,
      sym_symbol,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
    ACTIONS(89), 6,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      sym__identifier,
      anon_sym_SQUOTE,
  [555] = 5,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym__identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    STATE(46), 1,
      sym_symbol,
    STATE(10), 2,
      sym__dollar_symbol,
      sym__quoted_symbol,
  [572] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      aux_sym_list_repeat1,
  [582] = 3,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_struct_repeat1,
  [592] = 3,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    ACTIONS(97), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_list_repeat1,
  [602] = 3,
    ACTIONS(99), 1,
      anon_sym_COMMA,
    ACTIONS(102), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      aux_sym_list_repeat1,
  [612] = 3,
    ACTIONS(104), 1,
      anon_sym_COMMA,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym_struct_repeat1,
  [622] = 3,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      aux_sym_struct_repeat1,
  [632] = 1,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [637] = 2,
    ACTIONS(115), 1,
      anon_sym_COLON_COLON,
    STATE(38), 1,
      aux_sym_annotations_repeat1,
  [644] = 1,
    ACTIONS(111), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [649] = 1,
    ACTIONS(102), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [654] = 2,
    ACTIONS(118), 1,
      anon_sym_COLON_COLON,
    STATE(38), 1,
      aux_sym_annotations_repeat1,
  [661] = 1,
    ACTIONS(120), 2,
      aux_sym__dollar_symbol_token1,
      sym__identifier,
  [666] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [670] = 1,
    ACTIONS(124), 1,
      anon_sym_DQUOTE,
  [674] = 1,
    ACTIONS(126), 1,
      aux_sym__quoted_symbol_token1,
  [678] = 1,
    ACTIONS(128), 1,
      anon_sym_COLON_COLON,
  [682] = 1,
    ACTIONS(130), 1,
      anon_sym_COLON,
  [686] = 1,
    ACTIONS(132), 1,
      aux_sym_string_token1,
  [690] = 1,
    ACTIONS(134), 1,
      anon_sym_SQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 38,
  [SMALL_STATE(6)] = 76,
  [SMALL_STATE(7)] = 114,
  [SMALL_STATE(8)] = 149,
  [SMALL_STATE(9)] = 184,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 218,
  [SMALL_STATE(12)] = 235,
  [SMALL_STATE(13)] = 264,
  [SMALL_STATE(14)] = 283,
  [SMALL_STATE(15)] = 311,
  [SMALL_STATE(16)] = 339,
  [SMALL_STATE(17)] = 353,
  [SMALL_STATE(18)] = 381,
  [SMALL_STATE(19)] = 394,
  [SMALL_STATE(20)] = 407,
  [SMALL_STATE(21)] = 432,
  [SMALL_STATE(22)] = 445,
  [SMALL_STATE(23)] = 458,
  [SMALL_STATE(24)] = 471,
  [SMALL_STATE(25)] = 484,
  [SMALL_STATE(26)] = 497,
  [SMALL_STATE(27)] = 510,
  [SMALL_STATE(28)] = 523,
  [SMALL_STATE(29)] = 539,
  [SMALL_STATE(30)] = 555,
  [SMALL_STATE(31)] = 572,
  [SMALL_STATE(32)] = 582,
  [SMALL_STATE(33)] = 592,
  [SMALL_STATE(34)] = 602,
  [SMALL_STATE(35)] = 612,
  [SMALL_STATE(36)] = 622,
  [SMALL_STATE(37)] = 632,
  [SMALL_STATE(38)] = 637,
  [SMALL_STATE(39)] = 644,
  [SMALL_STATE(40)] = 649,
  [SMALL_STATE(41)] = 654,
  [SMALL_STATE(42)] = 661,
  [SMALL_STATE(43)] = 666,
  [SMALL_STATE(44)] = 670,
  [SMALL_STATE(45)] = 674,
  [SMALL_STATE(46)] = 678,
  [SMALL_STATE(47)] = 682,
  [SMALL_STATE(48)] = 686,
  [SMALL_STATE(49)] = 690,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dollar_symbol, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dollar_symbol, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_symbol, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__quoted_symbol, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotations, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotations, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_value_pair, 3, 0, 1),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_annotations_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [122] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_annotations_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_Ion(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
